version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dbtree
    main: ./cmd/dbtree
    binary: dbtree
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore arm64 for windows as it's less common
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: dbtree
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - UNLICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: viveknathani
    name: dbtree

  draft: false
  prerelease: auto

  name_template: "{{.ProjectName}} v{{.Version}}"

  header: |
    ## Installation

    ### Quick Install (Linux/macOS)
    ```bash
    curl -fsSL https://vivekn.dev/dbtree/install.sh | bash
    ```

    ### Manual Installation
    Download the appropriate binary for your platform from the assets below and extract it to your PATH.
